### ISSUE TITLE
feat: add dynamic configuration for rust using codelldb

### ISSUE THREAD

**Issue by pedrobarco** [jay-babu/mason-nvim-dap.nvim#107]
Hi, I'm using this plugin for managing my dap debuggers and I was trying to use the default configuration for `codelldb`.

My understanding is that you've provided an agnostic config to work with C/C++/Rust by always asking for the user to input the executable path.

I've started working on a way to improve our developer experience in `rust` by:
* building the app before debugging 
* parsing the build output to get the executable path from `cargo`
* fail in case we have an error building it

```lua
dap.configurations.rust = {
	{
		name = "LLDB: Launch",
		type = "codelldb",
		request = "launch",
		program = function()
			local output = vim.fn.systemlist("cargo build -q --message-format=json 2>1")
			for _, l in ipairs(output) do
				local json = vim.json.decode(l)
				if json == nil then
					error("error parsing json")
				end
				if json.success == false then
					return error("error building package")
				end
				if json.executable ~= nil then
					return json.executable
				end
			end
		end,
		cwd = "${workspaceFolder}",
		stopOnEntry = false,
		args = {},
	},
}
```

I'm not quite sure if this follows any best practices but I just wanted to share how I did it and hopefully get some feedback as to which kind of features you want to support in `mason-nvim-dap`. Would you be interested in having such features? Does it make sense to create something like this for other languages + debuggers? Let me know what you think.

**Comment by jay-babu** [comment]
I am not against having this builtin. I would just want to make this solution is generic and applies to all users of rust. anyway to confirm that?

**Comment by pedrobarco** [comment]
I'm fairly new to rust but using `cargo` is for sure the idiomatic way of building apps in rust (see [here](https://doc.rust-lang.org/book/ch01-03-hello-cargo.html)).

From what I've seen so far, we'll need to:
* run the `cargo build` based on the file you're on ([cargo workspaces](https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html))
* investigate a way to improve how we're parsing the error from `cargo build`
* add this new configuration to `rust` without adding it to our `codelldb` configurations (make this one only available for rust programs)
