### ISSUE TITLE
Not automatic install ensure_installed content

### ISSUE THREAD

**Issue by ccwanggl** [jay-babu/mason-nvim-dap.nvim#120]
In the init.lua file
``` 
"jay-babu/mason-nvim-dap.nvim",
        event = "BufRead",
        
        opts = function()
            return require "custom.plugins.configs.mason-dap"
        end,

        config = function(_, opts)
            require("mason-nvim-dap").setup(opts)
        end,
```

mason-dap.lua file return the table that want to be installed:

```
local options = {
    ensure_installed = {
        "prettier",
        "js-debug-adapter",
        "debugpy",
        "cpptools",
        "bash-debug-adapter"
    },
    
    automatic_installation = true,
}

-- if os_name == "Linux" then
--     table.remove(options.ensure_installed, get_os_name.tablefind(options.ensure_installed, "csharp_ls"))
-- end

return options
```

**Comment by jay-babu** [comment]
Is the problem ensure_installed isn't working or automatic_installation?

**Comment by jay-babu** [comment]
ensure_installed should include these names: https://github.com/jay-babu/mason-nvim-dap.nvim/blob/main/lua/mason-nvim-dap/mappings/source.lua

**Comment by jay-babu** [comment]
https://github.com/jay-babu/mason-nvim-dap.nvim/blob/main/lua/mason-nvim-dap/mappings/source.lua

**Comment by jay-babu** [comment]
https://github.com/jay-babu/mason-nvim-dap.nvim#available-dap-adapters

**Comment by ccwanggl** [comment]
Thanks for reply, I just known that the ensure_installed contents should be the programming language name, not debug tools name. Many thanks for your greate job!

**Comment by ccwanggl** [comment]
The ensure_installed contents should be as below:
```
local options = {
    ensure_installed = {
        "python",
        "bash",
        .......
    },
    
    automatic_installation = true,
}
```
