### ISSUE TITLE
DapInstall missing and DAP adapters are not automacally configured when using Lazy

### ISSUE THREAD

**Issue by AddictArts** [jay-babu/mason-nvim-dap.nvim#125]
Hi,

Using the Lazy config and I can't seem to get anything working. Here is my config

```
{
  "williamboman/mason.nvim",
  "mfussenegger/nvim-dap",
  "jay-babu/mason-nvim-dap.nvim",
  opts = {
    automatic_installation = true,
    handlers = {},
  },
}
```

**Comment by jay-babu** [comment]
you need to setup mason.nvim

**Comment by jay-babu** [comment]
and make both a dependency

**Comment by jay-babu** [comment]
this is invalid syntax for a lazy configy

**Comment by AddictArts** [comment]
> this is invalid syntax for a lazy configy

Thanks for the help. This config is right off the README for this project.

**Comment by jay-babu** [comment]
```
{
    "williamboman/mason.nvim",
    "mfussenegger/nvim-dap",
    "jay-babu/mason-nvim-dap.nvim",
}
```

are you referring to this? this is valid syntax haha. a bit confusing. this is probably along the line you want. untested

{
    { "williamboman/mason.nvim", config = true },
    "mfussenegger/nvim-dap",
    {"jay-babu/mason-nvim-dap.nvim", config = ..., 
        dependencies = {"williamboman/mason.nvim", "mfussenegger/nvim-dap"},
    },
}

**Comment by AddictArts** [comment]
@jay-babu I've used the config as you show and still no DapInstall. Checking Lazy the mason-nvim-dap is loaded.

**Comment by AddictArts** [comment]
I settled on this in my plugins which now results in DapInstall being present. However, I am unsure of the adapters and how to see if they were installed or available. I apologize I am new to this, lua, neovim, etc. 

````
return {
  "jay-babu/mason-nvim-dap.nvim",
  dependencies = { "williamboman/mason.nvim", "mfussenegger/nvim-dap" },
  opts = {
    automatic_installation = true,
    handlers = {},
  },
}
````
