### ISSUE TITLE
js-debug-adapter

### ISSUE THREAD

**Issue by cr4ftx** [jay-babu/mason-nvim-dap.nvim#127]
Hi there,

Thanks for this plugins 👍 

I have an issue when I configure the js-debug-adapter, this plugin maps js to js-debug-adapter.

But on the other hand, the js-debug-adapter only accept pwa-node, pwa-chrome, pwa-msedge, node-terminal, pwa-extensionHost.

So if I add an adapter like this : `dap.adapters["pwa-node"]` the auto install feature is not working (it expects js).

I managed to add js in the ensure_installed but I wanted to auto install adapters.

Is there any solution to this ?

**Comment by jay-babu** [comment]
@cr4ftx does the above PR meet your needs? It should from what I see

**Comment by cr4ftx** [comment]
Yeah it's going to do the job, but there are other options than `pwa-node` from what I can see from here https://code.visualstudio.com/docs/nodejs/nodejs-debugging and here https://github.com/mxsdev/nvim-dap-vscode-js.
I think someone should deep dive all of the options of the js-debug-adapter.

nvim-dap has already an option for loading vscode config (see `:h dap.ext.vscode.load_launchjs`) I think supporting this config would be awesome.
