### ISSUE TITLE
Prevent Mac OSX crash report pop-up at end of program

### ISSUE THREAD

**Issue by sammorley-short** [jay-babu/mason-nvim-dap.nvim#138]
When I run a python file through the debugger and either hit the end of the program, or quit the session, I always get a system crash report pop up, as shown below.

<img width="997" alt="Screenshot 2024-09-06 at 12 16 17" src="https://github.com/user-attachments/assets/3164d7fe-a1cd-49eb-985e-c84b9faa29e0">

This doesn't happen if I run `debugpy` outside of nvim, so is presumably an issue with its usage there.

Any advice on how to prevent this would be very helpful, thanks! 

(N.B. I know I can deactivate the crash reporter in general, but I don't want to do this for obvious reasons!)

**Comment by jay-babu** [comment]
https://github.com/jay-babu/mason-nvim-dap.nvim/blob/main/lua/mason-nvim-dap/mappings/configurations.lua#L58

https://github.com/jay-babu/mason-nvim-dap.nvim/blob/main/lua/mason-nvim-dap/mappings/adapters/delve.lua

see if any of these don't match your local

**Comment by sammorley-short** [comment]
@jay-babu Sorry for the slow response, but both of my copies of the files above match yours. Any idea what's going on?
