### ISSUE TITLE
Change PHP port from 9000 to 9003

### ISSUE THREAD

**Issue by DerekLeach** [jay-babu/mason-nvim-dap.nvim#140]
PHP Xdebug changed the default port for step debugging between V2 and V3:
https://xdebug.org/docs/upgrade_guide#Step-Debugging

Would it be possible to change the port in mappings/configurations.lua from port 9000 to 9003

This would also match the configuration suggested in nvim-dap:

https://github.com/mfussenegger/nvim-dap/wiki/Debug-Adapter-installation#php

**Comment by jay-babu** [comment]
I will merge in a PR

**Comment by danielcavanagh** [comment]
can this please be reopened?

xdebug 3 (port 9003) has been the default for a few years now and no currently maintained version of php even supports xdebug 2

https://xdebug.org/docs/compat#versions
https://www.php.net/supported-versions.php

cheers 🙂
