### ISSUE TITLE
Add interopability with mason-lspconfig

### ISSUE THREAD

**Issue by cwrau** [jay-babu/mason-nvim-dap.nvim#16]
I have https://github.com/williamboman/mason-lspconfig.nvim installed which automatically installs configures LSPs for me

This results in e.g. `pyright` in the `mason` packages.

Sadly this tool only looks for https://github.com/jayp0521/mason-nvim-dap.nvim/blob/main/lua/mason-nvim-dap/mappings/source.lua#L7 (`python`)

Could we expand the mapping to include various others, like `pyright`, to the corresponding DAP?

Like adding

```
	['pyright'] = 'debugpy',
```

or making the left side a list;

```
	{ 'python', 'pyright' } = 'debugpy',
```

which of course needed other changes, ....

Or maybe I'm using this wrong? How would I end up with a `python` folder in the packages? `mason` only returns it's own valid packages, which doesn't include `python`

**Comment by jay-babu** [comment]
Hello,

Maybe this will help clear some things up. The left side of the equal is the name of the debug adapter. It's not based on a random convention. Also, pyright is a specific implementation of a lsp checker for python. There might be others for python. It doesn't really make sense to bring the concept of lsp into this plugin. There is only so much abstraction you can give before you start getting opinionated on how things must be.

This plugin's goal is to simply take an adapter you want and install its dependencies and configure it to work with sane overridable defaults.

**Comment by cwrau** [comment]
Huh, ok, I thought

```
	--   - true: All servers set up via lspconfig are automatically installed.
	--   - { exclude: string[] }: All servers set up via mason-nvim-dap, except the ones provided in the list, are automatically installed.
	--       Example: automatic_installation = { exclude = { "python", "delve" } }
    automatic_installation = false,
```

meant that I can configure LSP and this would automatically install the required debug tool?

**Comment by jay-babu** [comment]
Sorry, that is my fault. Bad copy and paste from https://github.com/jay-babu/mason-null-ls.nvim

**Comment by jay-babu** [comment]
https://github.com/jay-babu/mason-nvim-dap.nvim/commit/897219537e732bf630425827f6b0851c7794e8ea

updated here

**Comment by cwrau** [comment]
Oh, I see 😕

Then I guess this won't be implemented?
