### ISSUE TITLE
js-debug-adapter configuration doesn't work

### ISSUE THREAD

**Issue by sahinakkayadev** [jay-babu/mason-nvim-dap.nvim#17]
I have installed `js-debug-adapter` with `:DapInstall js` but I can not start a debugging session with `:DapContinue`

`No configuration found for javascript. You need to add configs to dap.configurations.javascript (See :h dap-configuration).`

![image](https://user-images.githubusercontent.com/32161460/206309678-f66f112b-0995-4186-88ba-bbeedf64ccd1.png)

I also installed `firefox-debug-adapter` and it works fine. So there must be a problem with `js-debug-adapter`

**Comment by jay-babu** [comment]
Hmm I am not sure if that adapter should be there. Seems like it should not be there as there is no configuration in place for it.

I don't see a guide on to set it up. I will take a look tomorrow and see if I can find anything. If not, then I will have to remove it

https://github.com/mfussenegger/nvim-dap/wiki/Debug-Adapter-installation#javascript

**Comment by jay-babu** [comment]
It seems as `nvim-dap` doesn't officially support it, https://github.com/mfussenegger/nvim-dap/issues/82#issuecomment-761814861. Based on that, this plugin won't support `js-debug-adapter` either.

**Comment by sahinakkayadev** [comment]
OK, you can close this issue when you remove it from the repo.

This is not right place to ask but do you know how to debug a single javascript file? I tried `firefox-debug-adapter` , and it doesn't seem to work with a single file. Maybe I am missing something basic?

**Comment by jay-babu** [comment]
https://github.com/mfussenegger/nvim-dap/wiki/Debug-Adapter-installation#Javascript

you can check out this. This is supported by this plugin

**Comment by jay-babu** [comment]
https://github.com/jay-babu/mason-nvim-dap.nvim/blob/main/lua/mason-nvim-dap/mappings/source.lua#L10

**Comment by harrisoncramer** [comment]
It feels a bit odd to remove this since Mason does support _installing_ this debugger, and it works fine with this extension: https://github.com/mxsdev/nvim-dap-vscode-js

Any chance we could keep it in here, perhaps under a different name than "js" so folks aren't confused? It's the only debugger I have to manually install now. If not, I can fork this repo and add it back myself. Either way, thanks for the great plugin.

**Comment by entropitor** [comment]
I have the same problem as @harrisoncramer. 

Would it be possible to add it conditionally to avoid confusion? E.g. when you have https://github.com/mxsdev/nvim-dap-vscode-js installed, allow it to be installed through mason?

**Comment by dagadbm** [comment]
Me too. I'm trying to get this setup working and it is all very confusing due to all the different ways you have of installing these debuggers

**Comment by dagadbm** [comment]
Seems like there are some depending like:

https://github.com/microsoft/vscode-js-debug/issues/1388
https://github.com/mfussenegger/nvim-dap/issues/762

**Comment by lettertwo** [comment]
Here's a way to have our cake and eat it too:
```lua
-- HACK: Trick mason-nvim-dap into autoinstalling js debug adapter.
-- See: https://github.com/jay-babu/mason-nvim-dap.nvim/issues/17
require("mason-nvim-dap.mappings.source").nvim_dap_to_package["js"] = "js-debug-adapter"

require("mason-nvim-dap").setup({
  ensure_installed = { "js" },
  ...
})
```

**Comment by jay-babu** [comment]
Please create a PR. I will merge it back in. Thanks!

**Comment by jay-babu** [comment]
Reverted in the latest commit. Thanks for the feedback from everyone! Going forward all debuggers will be added to this plugin even if `automatic_setup` is not supported
