### ISSUE TITLE
Seeing an issue running in headless mode

### ISSUE THREAD

**Issue by hermitmaster** [jay-babu/mason-nvim-dap.nvim#27]
I have some aliases and plumbing set up for bootstrapping a new machine. One of the steps is to fire off packer to get all of my nvim plugins sorted. I get errors from this plugin (only when headless, works fine if I call `PackerSync` inside nvim). I'm happy to do anything I can to provide more details.

For what it's worth, Mason fails to install things quietly due to the nature of the `PackerComplete` event; it doesn't wait for hooks.

Thanks for the great plugin!

```
~/.config main* ❯ alias nps
nps='nvim --headless +'\''autocmd User PackerComplete qa'\'' +'\''PackerSync'\'

~/.config main* ❯ nps
[mason] [ERROR 14:45:46] ...pack/packe...t #1 to '?' (string expected, got nil)[mason] [ERROR 14:45:46] ...pack/packe...t #1 to '?' (string expected, got nil)[mason] [ERROR 14:45:48] ...pack/packe...t #1 to '?' (string expected, got nil)[mason] [ERROR 14:45:48] ...pack/packe...t #1 to '?' (string expected, got nil)
```

**Comment by jay-babu** [comment]
Based on the error messages, it seems to be a problem in mason? Maybe start with reporting the problem there. Happy to change stuff here if need be, but I think investigation can start there.

**Comment by jay-babu** [comment]
The error could be because of `ui.open()` unsure how it would affect headless mode. Do you have a minimal config I can replicate with?

**Comment by hermitmaster** [comment]
I’ll get a minimal config and share it here on Monday. As far as I can tell, anything that fires this plugin in headless mode should work.

**Comment by hermitmaster** [comment]
@jay-babu FYI - I actually opened this issue in the wrong repo. The issue I meant to report is https://github.com/jay-babu/mason-null-ls.nvim/issues/43
