### ISSUE TITLE
Automatic setup of cppdbg not working

### ISSUE THREAD

**Issue by motorto** [jay-babu/mason-nvim-dap.nvim#28]
When running DapContinue and after inserting the executable I get the following error:

> Error on Launch: Unable to start debugging. Launch options string provided by the project system is invalid. Unable to determine path to debugger. Please specify the "MIDebuggerPath" option

here is my  config:

```lua
 local dap_servers_to_install = { 'cppdbg' }
        
require('mason').setup()
require("mason-nvim-dap").setup({
  ensure_installed = dap_servers_to_install,
  automatic_setup = true,
})

require 'mason-nvim-dap'.setup_handlers()
```
https://user-images.githubusercontent.com/52639805/208263867-7bffb7c1-f49c-4434-a43f-3eb9bff2551b.mp4

**Comment by motorto** [comment]
It was me being dumb, I didn't have `gdb` installed...

**Comment by jay-babu** [comment]
Sorry, I looked into this yesterday. Forgot to reply
