### ISSUE TITLE
Add mapping support for type = "pwa-chrome" 

### ISSUE THREAD

**Issue by Taaqif** [jay-babu/mason-nvim-dap.nvim#32]
Some launch.json we work with contain `type = "pwa-chrome"` in the definition, it seems unanimous with the `type = chrome` definitions so would be interested to see what's involved with treating it the same

**Comment by jay-babu** [comment]
There is a way to override the configuration already. See Default Setup

```
automatic_setup = {
  chrome = {
     type = "pwa-chrome",
     ...
  },
}
```

This is an example. Does this address your concern?
