### ISSUE TITLE
Path to repository in 'Installation' README section outdated 

### ISSUE THREAD

**Issue by MateuszSadowski** [jay-babu/mason-nvim-dap.nvim#37]
Using "jayp0521/mason-nvim-dap.nvim" results in a "repository not found error".

Using "jay-babu/mason-nvim-dap.nvim" allows installing the plugin successfully.

**Comment by jay-babu** [comment]
https://github.com/jay-babu/mason-nvim-dap.nvim/commit/4feb21a598e690f947aa2c97129a469f772b5289

thanks for catching this!
