### ISSUE TITLE
Add go-debug-adapter

### ISSUE THREAD

**Issue by lucax88x** [jay-babu/mason-nvim-dap.nvim#45]
Can we add go-debug-adapter?

Thanks for the plugin!

**Comment by jay-babu** [comment]
Is there something wrong with https://github.com/jay-babu/mason-nvim-dap.nvim/blob/main/lua/mason-nvim-dap/mappings/adapters.lua#L11?

**Comment by lucax88x** [comment]
Sorry bud.

Wasn't aware delve is the dap for go.

May I suggest to add go to the list of source?

https://github.com/jay-babu/mason-nvim-dap.nvim/blob/main/lua/mason-nvim-dap/mappings/source.lua

**Comment by jay-babu** [comment]
https://github.com/jay-babu/mason-nvim-dap.nvim/blob/main/lua/mason-nvim-dap/mappings/source.lua#L9

it is there?

**Comment by lucax88x** [comment]
I asked to add "go" to that list.

But yes, now that I think about it I understand it's a list of adapters and not languages, so it makes sense.
