### ISSUE TITLE
Pinning Specific Versions

### ISSUE THREAD

**Issue by harrisoncramer** [jay-babu/mason-nvim-dap.nvim#47]
Hello,

Is it possible to pin specific versions of a debugger?

There were some recent updates to a debugger that broke my setup. In this particular case it was the move from `1.74.1` to `1.75` of https://github.com/microsoft/vscode-js-debug/releases.

I'd love to be able to pin the old version if possible. Thanks!

**Comment by jay-babu** [comment]
If you are using `ensure_installed`, then you can do something like `adapter@V` like `js@1.74.1`

**Comment by harrisoncramer** [comment]
Thanks for the reply! That gives me the following stack trace in Mason:

```
[INFO  Tue Feb 21 22:33:32 2023] ...e/nvim/lazy/mason.nvim/lua/mason-core/installer/init.lua:162: Executing installer for Package(name=js-debug-adapter) version="1.74.1"
[ERROR Tue Feb 21 22:33:35 2023] ...e/nvim/lazy/mason.nvim/lua/mason-core/installer/init.lua:192: Installation failed for Package(name=js-debug-adapter) error=spawn: git failed with exit code 128 and signal 0. 
```

To be clear, this is what I'm doing:

```
    local mason_dap = require("mason-nvim-dap")
    mason_dap.setup({
      ensure_installed = { "delve", "node2", "js@1.74.1" },
      automatic_installation = true
    })
```

The plugin and auto-installation is working without the `@` symbol, however (non-pinned). Perhaps I'm still doing something wrong?

**Comment by jay-babu** [comment]
Maybe you need the `v`?

**Comment by harrisoncramer** [comment]
Thank you!!
