### ISSUE TITLE
Unable to require default mappings (adapter, config, filetype etc) if `automatic_setup` is boolean

### ISSUE THREAD

**Issue by kofteistkofte** [jay-babu/mason-nvim-dap.nvim#49]
I know it's a bit of a strange way of using it, but I want to use manual adapter setup but for some adapter wanted to pull the default ones. If I try to call default adapters like `require('mason-nvim-dap.mappings.adapters')` I get an error like this:

`E5113: Error while calling lua chunk: ...n-nvim-dap.nvim/lua/mason-nvim-dap/mappings/adapters.lua:91: attempt to index field 'automatic_setup' (a boolean value)`

Which is expected because `automatic_setup` field is a boolean but it always tries to access `adapters` field in it.

This behavior can be fixed by adding a boolean/table check or slightly modify `func_or_extend` function.

I opened this issue to learn if the current behavior is "how things should work" or not. If not I can also open a PR for it.

**Comment by jay-babu** [comment]
Can you send a snippet of what you would like or ideally what you need?

**Comment by jay-babu** [comment]
like this should reset the default `php` configuration. does that not work?
```
require("mason-nvim-dap").setup({
    automatic_setup = {
        -- modifies the default configurations table
        -- pass in a function or a list to override with
        -- the same can be done for adapters and filetypes
        configurations = function(default)
            default.php = {}

            return default
        end,
   }
})
```
