### ISSUE TITLE
Ruby dap-udapter.

### ISSUE THREAD

**Issue by Starlexxx** [jay-babu/mason-nvim-dap.nvim#50]
Thank you for your plugin. Are you going to add any Ruby on Rails adapter?

**Comment by jay-babu** [comment]
Hello, 

Do you have an example? Open to PRs as well

**Comment by Starlexxx** [comment]
https://github.com/mfussenegger/nvim-dap/wiki/Debug-Adapter-installation#Ruby
Here is an example.

**Comment by jay-babu** [comment]
Per this, there doesn't seem to be a way to install the adapter via mason?

**Comment by Starlexxx** [comment]
I think, that it's similar to go-atapter, so I can try to add it in the near future.

**Comment by jay-babu** [comment]
@Starlexxx, i opened an issue here, https://github.com/williamboman/mason.nvim/issues/1117. once complete, we can add to this plugin

**Comment by Starlexxx** [comment]
Thank you!
