### ISSUE TITLE
Automatic setup doesn't work with codelldb on Windows

### ISSUE THREAD

**Issue by aosterhage** [jay-babu/mason-nvim-dap.nvim#51]
I want to preface by saying that I assume this will be the case for all adapters installed via `mason.nvim` on Windows.

I've installed `codelldb` via `mason.nvim` and done the typical setup:

```
require('mason').setup({})
require('mason-nvim-dap').setup({
  automatic_setup = true
})
require('mason-nvim-dap').setup_handlers({})
```

This does configure `dap.adapters.codelldb` but with the following values:

```
{
  executable = {
    args = { "--port", "${port}" },
    command = "codelldb",
    detached = false
  },
  port = "${port}",
  type = "server"
}
```

Running `:DapContinue` will prompt nvim-dap to ask for the executable location and once provided will error out on:

```
.../.local/share/nvim-data/lazy/nvim-dap/lua/dap/session.lua:1153: ENOENT: no such file or directory
```

Enabling DEBUG level logs in nvim-dap shows:

```
[ DEBUG ] 2023-03-23T15:37:56Z-0400 ] ....local/share/nvim-data/lazy/nvim-dap/lua/dap/session.lua:1120 ]	"Starting debug adapter server executable"	{
  args = { "--port", "${port}" },
  command = "codelldb",
  detached = false
}
```

which is the same configuration that `mason-nvim-dap.nvim` has setup via `automatic_setup`. The issue is that, for whatever reason, `codelldb` is not recognized as a file but `codelldb.cmd` is since this is the file actually installed by mason:

```
> ls ~/.local/share/nvim-data/mason/bin/
codelldb.cmd
```

If I modify the configuration like so:

```
:lua require('dap').adapters.codelldb.executable.command = 'codelldb.cmd'
```

then everything works great. But this defeats the purpose of `automatic_setup` for me.

I've been saying that I'm on Windows because I'm assuming its important but I don't actually know yet as I haven't tested on Linux (which I can if needed). I'm assuming Linux works or someone would have noticed by now.

**Comment by aosterhage** [comment]
Looks like (mason-lspconfig.nvim)[https://github.com/williamboman/mason-lspconfig.nvim] uses `vim.fn.exepath` but *only* for Windows platforms:

```
            if platform.is.win and (config.cmd and config.cmd[1] ~= "cmd.exe") then
                local exepath = vim.fn.exepath(config.cmd[1])
                if exepath ~= "" then
                    config.cmd[1] = exepath
                else
                    log.error("Failed to expand cmd path", config.name, config.cmd)
                end
            end
```

**Comment by jay-babu** [comment]
@aosterhage, do you mind creating a PR for codellb cmd changes? If everything works fine for a week or 2, this can be expanded to all other adapters. I am out of town otherwise I would do it right now

**Comment by aosterhage** [comment]
I replicated the same test as my previous comment in Linux and everything continued working as expected.

**Comment by jay-babu** [comment]
Thanks! Do you think it's a good idea to let this change boil for some time before applying everywhere?

**Comment by aosterhage** [comment]
I think either way is fine, waiting or not. I don't see much that can go wrong:

Something we should talk about is if there are any other implications of using `exepath`. It seems to me that `exepath` will find *any* executable in your path with the provided name.

If I look at my `PATH` in Neovim it looks like mason prepends its `bin` directory first so theoretically any call to `exepath` should resolve to the mason version first. But if you don't have any mason version installed and you *do* have one in your system PATH then `exepath` will happily use the system version. This doesn't feel like a huge issue since mason-nvim-dap only sets up configurations if an equivalent adapter is installed via mason.

If for some reason we want to specifically target only the mason binaries then we can do something like this:

```
require('mason-registry').get_package('codelldb'):get_install_path() .. '/extension/adapter/codelldb'
```

But I don't really like diving into the mason package paths when it provides a nice `stdpath('data')/mason` for us to access.

**Comment by aosterhage** [comment]
One more thing to consider before applying this to other adapters: do we want to only do this for Windows like mason-lspconfig with a `if platform.is.win`?

**Comment by jay-babu** [comment]
This can be expanded to use exepath for all places. I am not worried about if enforcing the mason dependency being installed. It has to be otherwise it won't work anyways. I can create a PR next week unless you want to. Thanks for finding this!

**Comment by aosterhage** [comment]
Thank you for the plugin!
