### ISSUE TITLE
Bug then opening

### ISSUE THREAD

**Issue by Bogdan-Torkhov** [jay-babu/mason-nvim-dap.nvim#56]
Installed bush dap with mason
And have these error when opening nvim: automatic setup can't found bash-debug-adapter with mason
Screen: https://www.mediafire.com/view/8b1mshlhgym393l/Screenshot_from_2023-04-01_23-03-51.png/file
Error in text: ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:79: Cann
ot find package "bash-debug-adapter".
...son-nvim-dap.nvim/lua/mason-nvim-dap/automatic_setup.lua:8: loop
or previous error loading module 'mason-nvim-dap.mappings.configurat
ions'

**Comment by Bogdan-Torkhov** [comment]
@jay-babu Help me, i checked the plugin code end there is no loops, and i have bash-debug-adapter installed and bashdb is also installed

**Comment by Bogdan-Torkhov** [comment]
I created a pull request that fixes these

**Comment by Bogdan-Torkhov** [comment]
And why don't you merge it?

**Comment by Bogdan-Torkhov** [comment]
@jay-babu where are you???

**Comment by jay-babu** [comment]
https://github.com/jay-babu/mason-nvim-dap.nvim/tree/bugfix/BASHDB_DIR

can you try this branch to see if it fixes the problem?

**Comment by Bogdan-Torkhov** [comment]
> https://github.com/jay-babu/mason-nvim-dap.nvim/tree/bugfix/BASHDB_DIR
> 
> can you try this branch to see if it fixes the problem?

Can you show me how to set these branch in lazy nvim

**Comment by Bogdan-Torkhov** [comment]
Checked

**Comment by Bogdan-Torkhov** [comment]
All working fine, you can merge it to main
