### ISSUE TITLE
setup_handlers() migration and default_setup() name confuses

### ISSUE THREAD

**Issue by herrvonvoid** [jay-babu/mason-nvim-dap.nvim#63]
hi, I just migrated from `setup_handlers()` to `setup({handlers = {...}})` and had a hard time to realize that you had to call `default_setup(customized_config)` in every custom handler. I would not expect a function which is to be used in custom handlers regularly to have "default" in it's name. Especially since you'd always call it - even when you overwrite the default handler, as then you'd just wrap it and do something extra before calling it. Therefore I believe a name like `setup_src(config)` would be more fitting.

I would also recommend to be more specific in the migration notes, which function you now have to call in every handler.

Awesome pluing,
kind regards

**Comment by jay-babu** [comment]
Let's keep this issue open to understand what people would like to see changed for its name.

For the docs confusion, are you able to add to the docs what you think is missing?
