### ISSUE TITLE
Improve documentation for Automatic Setup Usage

### ISSUE THREAD

**Issue by camezcua12** [jay-babu/mason-nvim-dap.nvim#65]
Hi, I was following [Kickstart.nvim](https://github.com/nvim-lua/kickstart.nvim), which includes this plugin as optional. After enabling it I had to solve issues with `setup_handlers` (outdated on their end), but even after that, I had the issue of getting no errors but still DAP adapters not being loaded in.

My config:

```
require('mason-nvim-dap').setup {
  automatic_setup = true,
  ensure_installed = {
    'chrome',
    'firefox',
    'php',
    'js',
  },
}
```
Automatic installation of related mason plugins worked fine, but still DAP would complain about no adapters being setup for given filetype. It was only after adding an empty `handler` object to my config that it started working:

```
require('mason-nvim-dap').setup {
  automatic_setup = true,
  ensure_installed = {
    'chrome',
    'firefox',
    'php',
    'js',
  },
  handlers = {},
}
```

As can be checked against current `README.md`, Automatic Setup doesn't state anywhere that this is necessary. Is there something I'm doing wrong or is the `handlers` value indeed required?

Other than that, brutal work!
Cheers!

**Comment by jay-babu** [comment]
Sorry, I updated mason null LS, but not here. I will do it today. Thanks!

**Comment by camezcua12** [comment]
Let me know if I should close the issue or you want to keep it up as a reminder!

**Comment by jay-babu** [comment]
https://github.com/jay-babu/mason-nvim-dap.nvim/commit/2b5f8a23d418e7efdf6dee569dd409bd1e807eae

**Comment by jay-babu** [comment]
updated docs
