### ISSUE TITLE
automatic setup takes ~400ms during config

### ISSUE THREAD

**Issue by meuter** [jay-babu/mason-nvim-dap.nvim#67]
Hi

I recently added `mason-nvim-dap` to my config. I am particularly interested in the `automatic_setup` feature, which work great BTW!  Thanks for that. 

However, since this addition I noticed that my startup time significantly increased. Using `nvim --headless --startuptime tmp/startup +qa`, I noticed that the adapter portion of `mason-nvim-dap` was taking around 400ms. Here is an extract of the profile:

```
120.316  000.826  000.826: require('mason-nvim-dap')
120.415  000.085  000.085: require('mason-nvim-dap.settings')
120.661  000.102  000.102: require('mason-nvim-dap.mappings.source')
120.676  000.242  000.141: require('mason-nvim-dap.ensure_installed')
543.765  422.617  422.617: require('mason-nvim-dap.mappings.adapters')              // this part requires 422ms apparently
543.871  000.098  000.098: require('mason-nvim-dap.mappings.filetypes')
544.023  000.066  000.066: require('mason-registry.index')
546.120  000.059  000.059: require('mason-core.functional.type')
592.397  048.523  048.397: require('mason-nvim-dap.mappings.configurations')
592.467  000.062  000.062: require('mason-nvim-dap.automatic_setup')
592.711  000.089  000.089: require('mason-nvim-dap.api.command')
```

and here the related extract of [my config](https://github.com/meuter/nvim/) (I use lazy):

```lua
return {
    "jay-babu/mason-nvim-dap.nvim",
    dependencies = {
        "williamboman/mason.nvim",
        "mfussenegger/nvim-dap",
    },
    config = function()
        require("mason-nvim-dap").setup {
            automatic_setup = true,
            ensure_installed = {
                "bash",
                "codelldb",
                "delve",
                "python"
            },
            handlers = {}
        }
    end
}
```

I thought that possibly one of the dap adapter in particular was at fault. So I tried commenting all of them in the `ensure_installed` section, but it does not seem to help. I am currently using this commit: b8b01c3.

If you need more info, or need me to run some experiment to help zoom in on the problem, let me know, I would be happy to help😄 

Thanks!

**Comment by jay-babu** [comment]
unfortunately, `vim.fn.exepath` may take awhile depending on how long your PATH is. I don't see a way around this since it is basically `which dlv`

https://github.com/jay-babu/mason-nvim-dap.nvim/blob/main/lua/mason-nvim-dap/mappings/adapters.lua

**Comment by jay-babu** [comment]
if you install all adapters, you should see a dramatic improvement in latency

**Comment by jay-babu** [comment]
`    ● mason-nvim-dap.nvim 1170.36ms   nvim-dap` is my current load time with only 3 adapters installed

`    ● mason-nvim-dap.nvim 48.41ms   nvim-dap` is my load time with all adapters installed

**Comment by meuter** [comment]
Hi @jay-babu 

Thanks for the reply! May I ask why do you need to lookup the executable in the path using `vim.fn.exepath`? wouldn't it be faster to use the mason install path? So instead of 

```lua
M.xxx = {
    -- ...
    command = vim.fn.exepath("xxx")
}
```

maybe this could be used: 

```lua
M.xxx = {
    -- ...
    command = vim.fn.stdpath("data") .. "/mason/bin/" .. "xxx" 
}
```

Of course this is the default path and could be overriden in the user's mason `config()` function. But there should be a way to query the install path from the `mason` package. The path seperator '/' should also probably be made to work on windows. But other than that, I don't see any downside - but hey I might be overlooking something here 😅 


I made a quick-and-dirty test in this [fork](https://github.com/meuter/mason-nvim-dap.nvim/commit/05c91bc4f87e0d2d9670b0a3445784a42cdd8305) and it seems to work rather well:

```bash
065.103  000.090  000.090: require('mason-nvim-dap.mappings.adapters')
```

All installed debugger seem to work as expected. If you're interested in pursuing this, let me know, I can try and contribute a PR.

Cheers!

**Comment by meuter** [comment]
Ok I had a quick look at mason, and there a pretty convenient function called [`bin_prefix`](https://github.com/williamboman/mason.nvim/blob/main/lua/mason-core/path.lua#L37) in `mason-core.path` that basically does exactly what I was proposing. Here is the [commit](https://github.com/meuter/mason-nvim-dap.nvim/commit/5ffc1ce259d095cc3a0006a4d9cbdbe6a8068454) in my fork. Works like a charm 🎉

**Comment by jay-babu** [comment]
I would prefer to not do this and get it from the path. There are other benefits like `.cmd` being appended automatically. you can override the `$PATH` variable in nvim if you want and make it shorter. it would bring the time down drastically

**Comment by meuter** [comment]
By `.cmd` I assume you mean the `.exe` file extension on windows. That would indeed be a good reason to keep `vim.fn.exepath`. But your proposal to play around with the `PATH` got me to investigate and I discovered something. I am primarily running neovim in a WSL box. And I discovered, to my surprise that the Windows host's `PATH` is exported in the WSL box. So my path was cluttered dozens of `/mnt/c/Program Files/...`. Once I removed these from the `PATH`, the 400ms vanished:

```bash
133.559  002.207  002.207: require('mason-nvim-dap.mappings.adapters')
```

So it would seem that the problem was on my end after all 🤦‍♂️ 
In any case, problem solved. Thanks again for the help. Much appreciated!

**Comment by meuter** [comment]
for anyone reaching this issue, this is how I ended up fixing the slow startup on WSL. It's a bit brute force, but effective.
```
-------------------------------------------------------------------------------
-- Fixup Path for WSL
-------------------------------------------------------------------------------
if vim.fn.getenv("WSLENV") ~= nil then
    -- on WSL the path is littered with the Windows hosts's PATH which
    -- slows down vim.fn.exepath
    local path = vim.fn.getenv("PATH")
    local fixed = {}
    for _, entry in ipairs(vim.fn.split(path, ":")) do
        if not string.match(entry, "/mnt/c/.*") then
            fixed[#fixed + 1] = entry
        end
    end
    local fixed_path = table.concat(fixed, ":")
    vim.fn.setenv("PATH", fixed_path)
end
```

I am but no means a lua expert, so there might be faster/more efficient ways of doing this, but it gets the job done.
