### ISSUE TITLE
vscode launch json does not work properly anymore

### ISSUE THREAD

**Issue by mintelm** [jay-babu/mason-nvim-dap.nvim#71]
Hello, one of the latest commits broke my setup, but I do not know why, maybe it's a bug, maybe it's because of breaking changes.  

So I'm using a vscode launch.json to configure my dap in a cpp project using the mason package `cpptools`. My configuration was fine in b4af78dd862e465dfc00ce7a4c0dd811fafb09ed. However, since 2b5f8a23d418e7efdf6dee569dd409bd1e807eae, my configuration broke and always returns the following message, when I try to start the debugger: `The selected configuration references adapter 'cppdbg', but dap.adapters.cppdbg is undefined`.

Configuration for mason-dap:
```
    if vim.fn.filereadable('.vscode/launch.json') then
        -- map launch.json type to filetypes (e.g. cppdbg = { 'c', 'cpp' })
        require('dap.ext.vscode').load_launchjs(nil, { cppdbg = { 'c', 'cpp' } })
    end
```

.vscode/launch.json:
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "gdb: launch test",
      "type": "cppdbg",
      "request": "launch",
      "program": "${workspaceFolder}/build/test_main",
      "args": [],
      "cwd": "${workspaceFolder}",
      "linux": {
        "MIMode": "gdb"
      },
      "windows": {},
      "setupCommands": [
        {
          "description": "Enable pretty-printing for gdb",
          "text": "-enable-pretty-printing",
          "ignoreFailures": true
        }
      ]
    }
  ]
}
```
I hope someone can help me, or atleast point me in the right direction. Thanks in advance :)

**Comment by jay-babu** [comment]
The release of 2.0 had breaking changes. See release section

**Comment by mintelm** [comment]
Ah, I missed that handlers have to be setup additionally now too. Thanks, got it running again. Closing the issue.
