### ISSUE TITLE
Some adapters are not found

### ISSUE THREAD

**Issue by eelcocramer** [jay-babu/mason-nvim-dap.nvim#73]
Some adapters that are in `source.lua` are not present in the (new) adapter folder. This generates errors when starting nvim. When I comment out `javadbg`, `javatest` and `php` everything seems to work fine.

Should these adapters still be added?

Thanks!

**Comment by jbpros** [comment]
Thanks for fixing this. 

I'm quite new to the whole neovim ecosystem. I managed to check out the v2.0.1 tag but Lazy keeps fetching the broken v2.0.2 release tag and updates automatically. Should the v2.0.2 tag be deleted as well?

**Comment by eelcocramer** [comment]
Just delete the v2.0.2 tag from your local clone. i.e. `git tag -d v2.0.2` after checking out the v2.0.1 tag.

**Comment by jbpros** [comment]
Thanks -- yep, I already did that but Lazy keeps fetching the tag from the remote 🤪

**Comment by eelcocramer** [comment]
I see ;-)

**Comment by ebruning** [comment]
I added the 2.0.1 tag like they did [here](https://github.com/jay-babu/mason-nvim-dap.nvim/issues/74#issuecomment-1516221414) and that resolved the issue

**Comment by jbpros** [comment]
@ebruning thanks, that worked!

**Comment by jay-babu** [comment]
deleted tag

**Comment by jay-babu** [comment]
issue should be solved

**Comment by jbpros** [comment]
all good here, thanks!
