### ISSUE TITLE
Packer Update Fails

### ISSUE THREAD

**Issue by AndreM222** [jay-babu/mason-nvim-dap.nvim#89]
When I try to update all my plugins this one alwasy says fail. the installation is the following.

use 'jay-babu/mason-nvim-dap.nvim'

Installer: Packer

Config: https://github.com/AndreM222/Windows-Dotfiles/blob/be551779a09be90f21c98b411823d91eb73df7d7/nvim/lua/andrem222/plugins.lua#L47

![image](https://user-images.githubusercontent.com/98118238/235311500-e04c5e99-1f8a-4123-b314-e47e3da29be7.png)

**Comment by jay-babu** [comment]
Can you show more info?

**Comment by AndreM222** [comment]
![image](https://user-images.githubusercontent.com/98118238/235352997-84228a0b-5e30-44f2-86dd-89eaec5071be.png)

**Comment by jay-babu** [comment]
Try deleting and reinstalling

**Comment by AndreM222** [comment]
Yes reinstalling worked. thanks
