### ISSUE TITLE
How can I config RUST configuration with mason-dap

### ISSUE THREAD

**Issue by duanyuluo** [jay-babu/mason-nvim-dap.nvim#92]
HI,  I have a problem of config rust dap.
I want to add my configuration for launching and use mason-dap's default adapter config(you known rust adapter config is complex...). 

FYI: 
1)   I leave codelldb in ensure_installed due to mason-dap map the rust filetype to codelldb and config codelldb adapter. 
2)  I can debug correctly these rust cargo projects without these new configuration. So I think rust-tool and codelldb debug server is OK.

error is: 
Failed to run `config` for rust-tools.nvim

...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:80: Cannot find package "codelldb".

# stacktrace:
  - /mason.nvim/lua/mason-registry/init.lua:80 _in_ **get_package**
  - /astrocommunity/lua/astrocommunity/pack/rust/rust.lua:17 _in_ **values**
  - /opt/homebrew/Cellar/neovim/0.9.0/share/nvim/runtime/filetype.lua:22
  - /opt/homebrew/Cellar/neovim/0.9.0/share/nvim/runtime/filetype.lua:21

lua code are below...

```lua
{
    "jay-babu/mason-nvim-dap.nvim",
    require("mason-nvim-dap").setup {
      automatic_setup = true,
      ensure_installed = {
        "python",
        "codelldb",
      },
      handlers = {
        function(config)
          -- all sources with no handler get passed here
          -- Keep original functionality
          require("mason-nvim-dap").default_setup(config)
        end,
        codelldb = function(config)
          config.configurations = {
            {
              name = "LLDB: Launch(codellde.log ENABLED)",
              type = "codelldb",
              request = "launch",
              program = function()
                return vim.fn.input(">>Path to executable: ", vim.fn.getcwd() .. "/target/debug/", "file")
              end,
              cwd = "${workspaceFolder}",
              stopOnEntry = true,
              args = {
                -- https://github.com/vadimcn/codelldb/wiki/LLDB-Logging
                -- initCommands = { "log enable gdb-remote default", "log enable lldb default" },
              },
            },
          }
          require("mason-nvim-dap").default_setup(config) -- don't forget this!
        end,
      },
    },
  },
}
```

**Comment by Je12emy** [comment]
bump

**Comment by AddictArts** [comment]
Hopefully you found this https://github.com/mrcjkb/rustaceanvim
