### ISSUE TITLE
Is nvim-dap-python unnecessary with this plugin?

### ISSUE THREAD

**Issue by kuator** [jay-babu/mason-nvim-dap.nvim#95]
Does `mason-nvim-dap.nvim` render https://github.com/mfussenegger/nvim-dap-python redundant? `nvim-dap-python` provides automatic configuration for python, but as far I understand, so does `mason-nvim-dap.nvim`.

**Comment by jay-babu** [comment]
it is not necessarily needed. thought the plugin might support more stuff than what DAP does

**Comment by kuator** [comment]
Thanks for the clarification
