### ISSUE TITLE
CodeLLDB don't work properly with c++

### ISSUE THREAD

**Issue by flame-222** [jay-babu/mason-nvim-dap.nvim#98]
## CodeLLDB don't work properly with C++
When I use codelldb to debug a code,it doesn't stop at the breakpoint,just run through
![image](https://github.com/jay-babu/mason-nvim-dap.nvim/assets/60837773/0cbce588-bda6-4f78-99c7-f238d4c0e10a)

REMARKS:It works properly in rust.I don't know why.

**Comment by jay-babu** [comment]
I don't really use CodeLLDB. This is mostly community given. Would you be able to see what is missing in C++ in the config. i will try to set this up for myself

**Comment by flame-222** [comment]
I know what's the problem. I forget to compile with "-g" command.How silly I am!

**Comment by brokoli18** [comment]
Just spent hours debugging the same issue to arrive at the same conclusion as @flame-222 :facepalm:
