### ISSUE TITLE
If you move the current directory, it will stop working. I don't know the cause.

### ISSUE THREAD

**Issue by RyuhoW** [jay-babu/mason-nvim-dap.nvim#99]
When I start neovim from the mason directory it works, but when I move the directory and try to start dap it doesn't work. Could I ask the reason.
![スクリーンショット 2023-06-21 185155](https://github.com/jay-babu/mason-nvim-dap.nvim/assets/91456393/3dc5dde0-6a6d-4d3b-977e-2ce5217c5455)
![スクリーンショット 2023-06-21 185324](https://github.com/jay-babu/mason-nvim-dap.nvim/assets/91456393/62a628d3-c023-4a1b-ae85-6cfb743c28be)

![スクリーンショット 2023-06-21 185459](https://github.com/jay-babu/mason-nvim-dap.nvim/assets/91456393/683dbf06-b704-444f-b56f-c4ececa49774)
![スクリーンショット 2023-06-21 185412](https://github.com/jay-babu/mason-nvim-dap.nvim/assets/91456393/fea469ad-21da-4f52-9036-cbf3f58b4bce)

I have the same issue with other than php

------------------------------------configuration-------------------------------------------------
require('mason-nvim-dap').setup({`
  ensure_installed = servers,
  handlers = {
    function(config)
      -- all sources with no handler get passed here

      -- Keep original functionality
      require('mason-nvim-dap').default_setup(config)
    end,

    cpp = function(config)
      config.adapters = {
        id = 'cppdbg',
        type = 'executable',
        command = '/usr/local/bin/extension/debugAdapters/bin/OpenDebugAD7',
      }

      config.configurations = {
        {
          name = "Launch file",
          type = "cppdbg",
          request = "launch",
          program = function()
            return vim.fn.input('Path to executable: ', vim.fn.getcwd() .. '/', 'file')
          end,
          cwd = '${workspaceFolder}',
          stopAtEntry = true,
        },
      }
      require('mason-nvim-dap').default_setup(config) -- don't forget this!
    end,

    php = function(config)
      config.adapters = {
        type = 'executable',
        command = 'node',
        args = { '/usr/local/bin/vscode-php-debug/out/phpDebug.js' }
      }

      config.configurations = {
        {
          type = 'php',
          request = 'launch',
          name = 'Listen for Xdebug',
          port = 9003,
          program = "${file}", -- This configuration will launch the current file if used.
        },
      }
      require('mason-nvim-dap').default_setup(config) -- don't forget this!
    end,
  },
})

----------------------------------end----------------------------------

**Comment by jay-babu** [comment]
Need to support hot reload? Not a problem with this plugin

**Comment by RyuhoW** [comment]
I realized a serious mistake. There was a bug because nvim-dap was called twice by require. It was solved by removing one.
